### ISSUE TITLE
How build localhost

### ISSUE THREAD

**Issue by hataiit9x** [spoqa/slack-translator#24]
I was a new develop
Please guide me step by step
thank you !

**Comment by hataiit9x** [comment]
2019-10-03T15:26:29.831402+00:00 heroku[web.1]: Starting process with command `gunicorn app:app`
2019-10-03T15:26:33.228763+00:00 heroku[web.1]: State changed from starting to up
2019-10-03T15:26:32.856174+00:00 app[web.1]: [2019-10-03 15:26:32 +0000] [4] [INFO] Starting gunicorn 19.3.0
2019-10-03T15:26:32.857498+00:00 app[web.1]: [2019-10-03 15:26:32 +0000] [4] [INFO] Listening at: http://0.0.0.0:45037 (4)
2019-10-03T15:26:32.857713+00:00 app[web.1]: [2019-10-03 15:26:32 +0000] [4] [INFO] Using worker: sync
2019-10-03T15:26:32.863008+00:00 app[web.1]: [2019-10-03 15:26:32 +0000] [10] [INFO] Booting worker with pid: 10
2019-10-03T15:26:32.961441+00:00 app[web.1]: [2019-10-03 15:26:32 +0000] [12] [INFO] Booting worker with pid: 12
2019-10-03T15:26:33.406664+00:00 app[web.1]: [2019-10-03 15:26:33 +0000] [10] [ERROR] Exception in worker process:
2019-10-03T15:26:33.406688+00:00 app[web.1]: Traceback (most recent call last):
2019-10-03T15:26:33.406692+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
2019-10-03T15:26:33.406694+00:00 app[web.1]: worker.init_process()
2019-10-03T15:26:33.406696+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 118, in init_process
2019-10-03T15:26:33.406698+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2019-10-03T15:26:33.4067+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
2019-10-03T15:26:33.406702+00:00 app[web.1]: self.callable = self.load()
2019-10-03T15:26:33.406704+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2019-10-03T15:26:33.406706+00:00 app[web.1]: return self.load_wsgiapp()
2019-10-03T15:26:33.406708+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2019-10-03T15:26:33.40671+00:00 app[web.1]: return util.import_app(self.app_uri)
2019-10-03T15:26:33.406712+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 355, in import_app
2019-10-03T15:26:33.406714+00:00 app[web.1]: __import__(module)
2019-10-03T15:26:33.406716+00:00 app[web.1]: File "/app/app.py", line 50, in <module>
2019-10-03T15:26:33.406717+00:00 app[web.1]: app = make_app(os.environ)
2019-10-03T15:26:33.406719+00:00 app[web.1]: File "/app/app.py", line 30, in make_app
2019-10-03T15:26:33.406721+00:00 app[web.1]: app.config.update(BROKER_URL=env['REDIS_URL'],
2019-10-03T15:26:33.406723+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/os.py", line 669, in __getitem__
2019-10-03T15:26:33.406725+00:00 app[web.1]: raise KeyError(key) from None
2019-10-03T15:26:33.406727+00:00 app[web.1]: KeyError: 'REDIS_URL'
2019-10-03T15:26:33.406729+00:00 app[web.1]: Traceback (most recent call last):
2019-10-03T15:26:33.406731+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
2019-10-03T15:26:33.406732+00:00 app[web.1]: worker.init_process()
2019-10-03T15:26:33.406734+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 118, in init_process
2019-10-03T15:26:33.406736+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2019-10-03T15:26:33.406738+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
2019-10-03T15:26:33.40674+00:00 app[web.1]: self.callable = self.load()
2019-10-03T15:26:33.406742+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2019-10-03T15:26:33.406744+00:00 app[web.1]: return self.load_wsgiapp()
2019-10-03T15:26:33.406746+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2019-10-03T15:26:33.406748+00:00 app[web.1]: return util.import_app(self.app_uri)
2019-10-03T15:26:33.40675+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 355, in import_app
2019-10-03T15:26:33.406752+00:00 app[web.1]: __import__(module)
2019-10-03T15:26:33.406754+00:00 app[web.1]: File "/app/app.py", line 50, in <module>
2019-10-03T15:26:33.406756+00:00 app[web.1]: app = make_app(os.environ)
2019-10-03T15:26:33.406758+00:00 app[web.1]: File "/app/app.py", line 30, in make_app
2019-10-03T15:26:33.406759+00:00 app[web.1]: app.config.update(BROKER_URL=env['REDIS_URL'],
2019-10-03T15:26:33.406761+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/os.py", line 669, in __getitem__
2019-10-03T15:26:33.406763+00:00 app[web.1]: raise KeyError(key) from None
2019-10-03T15:26:33.407129+00:00 app[web.1]: KeyError: 'REDIS_URL'
2019-10-03T15:26:33.407621+00:00 app[web.1]: [2019-10-03 15:26:33 +0000] [10] [INFO] Worker exiting (pid: 10)
2019-10-03T15:26:33.689441+00:00 app[web.1]: [2019-10-03 15:26:33 +0000] [12] [ERROR] Exception in worker process:
2019-10-03T15:26:33.689456+00:00 app[web.1]: Traceback (most recent call last):
2019-10-03T15:26:33.689458+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
2019-10-03T15:26:33.68946+00:00 app[web.1]: worker.init_process()
2019-10-03T15:26:33.689462+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 118, in init_process
2019-10-03T15:26:33.689464+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2019-10-03T15:26:33.689467+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
2019-10-03T15:26:33.689469+00:00 app[web.1]: self.callable = self.load()
2019-10-03T15:26:33.689471+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2019-10-03T15:26:33.689473+00:00 app[web.1]: return self.load_wsgiapp()
2019-10-03T15:26:33.689475+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2019-10-03T15:26:33.689477+00:00 app[web.1]: return util.import_app(self.app_uri)
2019-10-03T15:26:33.689479+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 355, in import_app
2019-10-03T15:26:33.689481+00:00 app[web.1]: __import__(module)
2019-10-03T15:26:33.689483+00:00 app[web.1]: File "/app/app.py", line 50, in <module>
2019-10-03T15:26:33.689485+00:00 app[web.1]: app = make_app(os.environ)
2019-10-03T15:26:33.689487+00:00 app[web.1]: File "/app/app.py", line 30, in make_app
2019-10-03T15:26:33.689489+00:00 app[web.1]: app.config.update(BROKER_URL=env['REDIS_URL'],
2019-10-03T15:26:33.689491+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/os.py", line 669, in __getitem__
2019-10-03T15:26:33.689493+00:00 app[web.1]: raise KeyError(key) from None
2019-10-03T15:26:33.689495+00:00 app[web.1]: KeyError: 'REDIS_URL'
2019-10-03T15:26:33.689501+00:00 app[web.1]: Traceback (most recent call last):
2019-10-03T15:26:33.689503+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
2019-10-03T15:26:33.689504+00:00 app[web.1]: worker.init_process()
2019-10-03T15:26:33.689506+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 118, in init_process
2019-10-03T15:26:33.689508+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2019-10-03T15:26:33.68951+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
2019-10-03T15:26:33.689512+00:00 app[web.1]: self.callable = self.load()
2019-10-03T15:26:33.689514+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2019-10-03T15:26:33.689515+00:00 app[web.1]: return self.load_wsgiapp()
2019-10-03T15:26:33.689517+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2019-10-03T15:26:33.689519+00:00 app[web.1]: return util.import_app(self.app_uri)
2019-10-03T15:26:33.689521+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 355, in import_app
2019-10-03T15:26:33.689523+00:00 app[web.1]: __import__(module)
2019-10-03T15:26:33.689525+00:00 app[web.1]: File "/app/app.py", line 50, in <module>
2019-10-03T15:26:33.689527+00:00 app[web.1]: app = make_app(os.environ)
2019-10-03T15:26:33.689528+00:00 app[web.1]: File "/app/app.py", line 30, in make_app
2019-10-03T15:26:33.68953+00:00 app[web.1]: app.config.update(BROKER_URL=env['REDIS_URL'],
2019-10-03T15:26:33.689532+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/os.py", line 669, in __getitem__
2019-10-03T15:26:33.689534+00:00 app[web.1]: raise KeyError(key) from None
2019-10-03T15:26:33.689542+00:00 app[web.1]: KeyError: 'REDIS_URL'
2019-10-03T15:26:33.689852+00:00 app[web.1]: [2019-10-03 15:26:33 +0000] [12] [INFO] Worker exiting (pid: 12)
2019-10-03T15:26:33.816869+00:00 app[web.1]: Traceback (most recent call last):
